config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  resources :islands do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:update, :destroy]

  get "dashboard", to: "pages#dashboard"
  get "about", to: "pages#about"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :island
end

app/models/island.rb
class Island < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  has_many :islands
  has_many :bookings
  has_many :received_bookings, through: :islands, source: :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # def new
  #   @island = Island.find(params[:island_id])
  #   @bookings = Booking.new
  # end

  def create
    @island = Island.find(params[:island_id])
    @booking = Booking.new(booking_params)
    @booking.island_id = params[:island_id]
    @booking.user_id = current_user.id
    if @booking.save
      redirect_to dashboard_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    @booking = Booking.find(params[:id])
    if params[:status] == "true"
      @booking.update(status: true)
    elsif params[:status] == "false"
      @booking.update(status: false)
    end
    redirect_to dashboard_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status, :number_of_guests)
  end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def show
    @island = Island.find(params[:id])
    @bookings = Booking.new
  end

  def new
    @island = Island.new
  end

  def create
    @island = Island.new(island_params)
    @island.user_id = current_user.id
    if @island.save
      redirect_to island_path(@island)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @island = Island.find(params[:id])
  end

  def update
    @island = Island.find(params[:id])
    @island.update(island_params)
    redirect_to island_path(@island)
  end

  def destroy
    @island = Island.find(params[:id])
    @island.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def island_params
    params.require(:island).permit(:name, :description, :location, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @islands = Island.all
  end

  def dashboard
    @user = current_user.id
    @islands = Island.where(user_id: @user)
    @user_bookings = Booking.where(user_id: @user)
    @booked_islands = Island.joins(:bookings).where("bookings.user_id = ?", @user)
    @bookings = Booking.joins(:island).where("islands.user_id = ?", @user)
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<h1>Book Your Island Vacation</h1>
<%= simple_form_for [@island, @bookings] do |f| %>
  <%= f.input :start_date, as: :date %>
  <%= f.input :end_date, as: :date %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Send Booking Request", class: "btn btn-primary" %>
<% end %>

app/views/islands/edit.html.erb
<h1>Edit Island</h1>
<%= simple_form_for [@island] do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.input :price %>
  <%= f.submit %>
<% end %>

app/views/islands/new.html.erb
<div class="form-container form-small">
  <h1>Add New Island</h1>
  <%= simple_form_for [@island] do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :location %>
    <%= f.input :price, label: "Price per day" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Save Island", class: "button-green" %>
  <% end %>
</div>

app/views/islands/show.html.erb
<div class="show-container">
    <div class="show-text">
      <div>
        <p id="showpage-slogan">DISCOVER YOUR PARADISE</p>
        <h1><em>Exclusive island rentals await!</em></h1>
      </div>
      <div>
        <h2><%= @island.name %></h2>
        <p><i class="fa-solid fa-location-dot"></i> <strong><%= @island.location %></strong> | $<%= @island.price %> per day</p>
        <p><%= @island.description %></p>
      </div>


      <div class="edit-delete-links">
      <% if current_user.id == @island.user_id%>
        <%= link_to "Edit",
          edit_island_path(@island)
        %> |
        <%= link_to "Delete",
          island_path(@island),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
        %>
      <% end %>
      </div>
    </div>
      <div class="show-image">
       <% if @island.photo.attached? %>
          <%= cl_image_tag @island.photo.key %>
        <% else %>
          <img src="<%= @island.image %>" alt="<%= @island.name %>">
      <% end %>
      </div>
    </div>

<div class="form-container">
 <% unless current_user.id == @island.user_id%>
        <h1>Book Your Island Vacation</h1>
        <%= simple_form_for [@island, @bookings] do |f| %>
          <%= f.input :start_date, as: :date %>
          <%= f.input :end_date, as: :date %>
          <%= f.input :number_of_guests %>
          <%= f.submit "Send Booking Request", class: "button-green"%>
        <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParadiseEscape</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

  </head>

  <body>
    <div>
    <%= render "shared/navbar" %>
    <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-page-container">

  <div class="about-container">
    <div class="team-image">
      <img src="https://i.imghippo.com/files/H4IQ71724415516.webp" alt="Team Picture">
    </div>
    <div class="team-description">
        <h1>About Paradise Escape <i class="fa-solid fa-leaf"></i></h1>
        <p>Welcome to <strong>Paradise Escape</strong>, your gateway to the world’s most exclusive and breathtaking island getaways. We believe in the power of nature's beauty and the allure of pristine, secluded destinations. Our mission is to connect travelers with the hidden gems of the world—private islands that offer serenity, luxury, and unforgettable experiences.</p>
    </div>
  </div>


  <section class="section-story">
    <div class="team-description">
        <h1>Our Story</h1>
        <p>Paradise Escape was born out of a deep passion for travel and a desire to discover the most beautiful and untouched places on Earth. Our founders, avid travelers themselves, were inspired by their own experiences of seeking out tranquil island retreats away from the hustle and bustle of everyday life. They recognized a gap in the market for a platform that could offer access to these unique destinations and set out to create Paradise Escape.</p>
    </div>
  </section>

  <section class="section-story">
    <div class="team-description">
        <h1>Our Commitment to Sustainability</h1>
        <p>We are committed to protecting the natural beauty of the islands in our collection. We work closely with island owners to ensure that sustainable practices are in place, minimizing environmental impact while providing an unforgettable experience for our guests.</p>
    </div>
  </section>

  <div class="sections-container">
    <section class="section-story">
      <div class="team-description">
        <h1>What We Offer <i class="fa-solid fa-briefcase"></i></h1>
        <p id="offer-p">At Paradise Escape, we curate a collection of the world’s finest private islands, each offering a distinct experience. Whether you’re seeking a romantic getaway, a family vacation, or an adventurous retreat, we have an island that will meet your desires.</p>
        <p>Let Paradise Escape take you on a journey to some of the world’s most stunning and exclusive destinations. Whether you’re looking to unwind on a secluded beach, explore vibrant coral reefs, or simply enjoy the luxury of your own private island, we are here to make your dream vacation a reality.</p>
      </div>
    </section>

    <section class="section-story">
      <div class="team-description">
        <p><strong>Exclusive Access</strong><br>We partner with private island owners and luxury resorts to bring you exclusive access to islands that are otherwise inaccessible to the general public.</p>
        <p><strong>Luxury & Comfort</strong><br>Every island in our collection is carefully selected to ensure it meets our high standards of luxury, comfort, and privacy. From overwater bungalows to beachfront villas, our islands offer world-class amenities and stunning natural surroundings.</p>
        <p><strong>Personalized Experiences</strong><br>We understand that every traveler is unique. That’s why we offer personalized experiences tailored to your preferences, whether it’s a private chef preparing your meals, a guided snorkeling adventure, or a sunset cruise.</p>
      </div>
    </section>

  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="dashboard-container">

  <div class="dashboard-user-info">
    <img src="https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/no-profile-picture-icon.png" alt="User Avatar" class="user-avatar">
    <div>
      <h2>Welcome <%= current_user.name %>!</h2>
      <p><strong>Email:</strong> <%= current_user.email %></p>
    </div>
    <button class="button-green">
      <a href="<%= new_island_path %>">Upload My Island</a>
    </button>
  </div>

  <%# DASHBOARD %>
  <div class="dashboard-cards">

    <div class="dashboard-card">
      <h2>My Islands</h2>

      <%# CAROUSEL - MY ISLANDS %>
      <div class="carousel-container">
        <div class="carousel-view">
          <button id="prev-btn-islands" class="prev-btn">&#9664;</button>
          <div id="item-list-islands" class="item-list">
            <% @islands.each do |island| %>
              <div class="card-item-island">
                <a href="<%= island_path(island) %>" class="card-link">

                <% if island.photo.attached? %>
                  <%= cl_image_tag island.photo.key %>
                <% else %>
                  <img src="<%= island.image %>" alt="<%= island.name %>">
                <% end %>

                  <h3><%= island.name %></h3>
                  <p><i class="fa-solid fa-location-dot"></i> <%= island.location %></p>
                </a>
              </div>
            <% end %>
          </div>
          <button id="next-btn-islands" class="next-btn">&#9654;</button>
        </div>
      </div>
    </div>

    <div class="dashboard-card">
      <h2>My Bookings</h2>

      <%# CAROUSEL - MY BOOKINGS %>
      <div class="carousel-container">
        <div class="carousel-view">
          <button id="prev-btn-bookings" class="prev-btn">&#9664;</button>
          <div id="item-list-bookings" class="item-list">
            <% unless @user_bookings.empty? %>
              <% @user_bookings.each do |booking| %>
                <div class="card-item">
                  <h3>Booking ID: <%= booking.id %></h3>
                  <p><span class = bold>Island ID:</span> <%= booking.island_id %></p>
                  <p><span class = bold>Number of Guests:</span> <%= booking.number_of_guests %></p>
                  <p><span class = bold>Your island getaway at:</span> <%= booking.island.name %>, <%= booking.island.location %> (<%= booking.number_of_guests %> guests)</p>
                  <p><span class = bold>Booking dates:</span> <%= booking.start_date%>-<%= booking.end_date %> (<%= (booking.end_date - booking.start_date).to_i %> days)</p>
                   
                  <% if booking.status == true %>
                      <p><span class = bold>Booking status:</span> Confirmed</p>
                    <% elsif booking.status == false %>
                      <p><span class = bold>Booking status:</span> Declined</p>
                    <% else %>
                     <p><span class = bold>Booking status:</span> Pending</p>
                  <% end %> 
            
                  <p><span class = bold>Total Price:</span> $<%= (booking.end_date - booking.start_date).to_i * booking.island.price %> ($<%= booking.island.price %>/day)</p>
                  <%= link_to "Delete", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'delete-btn' %>
                </div>
              <% end %>
            <% else %>
              <p>No bookings yet.</p>
            <% end %>
          </div>
          <button id="next-btn-bookings" class="next-btn">&#9654;</button>
        </div>
      </div>
    </div>

    <div class="dashboard-card">
      <h2>Bookings for My Islands</h2>
      <%# CAROUSEL - BOOKINGS FOR MY ISLANDS %>
      <div class="carousel-container">
        <div class="carousel-view">
          <button id="prev-btn-island-bookings" class="prev-btn">&#9664;</button>
          <div id="item-list-island-bookings" class="item-list">
            <% unless @bookings.empty? %>
              <% @bookings.each do |booking| %>
                <div class="card-item">

                  <h3>Booking: #<%= booking.id %></h3>
                  <p><%= booking.island.name %></p>
                  <p><%= booking.start_date%>-<%= booking.end_date %> (<%= (booking.end_date - booking.start_date).to_i %> days)</p>
                  <p><span class = bold>Number of Guests:</span> <%= booking.number_of_guests %></p>
                 <% if booking.status == true %>
                  <p><span class = bold>Booking Status:</span> Confirmed</p>
                  <% elsif booking.status == false %>
                    <p>Booking status: Declined</p>
                  <% else %>
                    <p>Booking status: Pending</p>
                 <% end %>
                  
                  <div class="booking-actions">
                    <%= link_to "Accept", booking_path(booking, status: true), data: { turbo_method: :patch }, class: "accept-link" %> |
                    <%= link_to "Decline", booking_path(booking, status: false), data: { turbo_method: :patch }, class: "decline-link" %>
                  </div>

                </div>
              <% end %>
            <% else %>
              <p>No bookings yet.</p>
            <% end %>
          </div>
          <button id="next-btn-island-bookings" class="next-btn">&#9654;</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render "shared/banner" %>
<%= render "shared/cards" %>

app/views/shared/_banner.html.erb
<div class="banner-container">
  <div class="banner-content">
    <h1><strong>Paradise Escape</strong></h1>
    <p>Discover and Rent Your Own Private Island Getaway</p>
  </div>
</div>

app/views/shared/_cards.html.erb
<div class="card-container">
  <div class="cards">
    <% @islands.each do |island| %>
        <a href="<%= island_path(island) %>" class="card-link">
          <div class="card">
            <% if island.photo.attached? %>
              <%= cl_image_tag island.photo.key %>
            <% else %>
              <img src="<%= island.image %>" alt="<%= island.name %>">
            <% end %>
            <h2><%= island.name %></h2>
            <p><i class="fa-solid fa-location-dot"></i> <strong><%= island.location %></strong> | <em>$<%= island.price %>/day</em></p>
            <p><%= island.description %></p>
          </div>
        </a>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-content">
    <ul class="footer-menu">
      <li class="footer-item">
        <a class="footer-link" href="#"><i class="fa-brands fa-facebook"></i></a>
      </li>
      <li class="footer-item">
        <a class="footer-link" href="#"><i class="fa-brands fa-instagram"></i></a>
      </li>
      <li class="footer-item">
        <a class="footer-link" href="#"><i class="fa-brands fa-youtube"></i></a>
      </li>
      <li class="footer-item">
        <a class="footer-link" href="#"><i class="fa-brands fa-x-twitter"></i></a>
      </li>
    </ul>
    <div class="footer-p">
      <p>© 2024 Paradise Escape. All rights reserved.</p>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="navbar-content">
    <ul class="navbar-menu">
      <li class="nav-item">
        <a class="nav-link" href="<%= root_path %>">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= about_path %>">About</a>
      </li>
      <a class="navbar-brand" href="<%= root_path %>">PARADISE ESCAPE</a>
      <li class="nav-item">
        <a class="nav-link" href="#">Contact</a>
      </li>

      <div class="dropdown">
        <% if user_signed_in? %>
        <button class="btn dropdown-toggle btn-navbar-green" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
          My Account
        </button>
           <ul class="dropdown-menu dropdown-menu-green" aria-labelledby="dropdownMenuButton2">
            <li class="nav-item dropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            </li>
            <li class="nav-item dropdown">
              <%= link_to "Add Island", new_island_path, class: "dropdown-item" %>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li class="nav-item dropdown">
             <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </li>
           </ul>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
        <% end %>
    </ul>
  </div>
</nav>